- hosts: all
  become: yes
  tasks:
    - name: Install the nginx packages
      yum: name="{{ item }}" state=present      
      with_items: nginx  
      when: ansible_os_family == "RedHat"

    - name: Install the nginx packages
      apt: name="{{ item }}" state=latest
      with_items: 
        - nginx         
        - apache2
      environment: env  
      when: ansible_os_family == "Debian"
















